### ISSUE TITLE
CompilerException java.lang.Exception when trying to require

### ISSUE THREAD

**Issue by luxbock** [helpshift/gulfstream#2]
With a project with just the following dependencies:

``` clojure
[[org.clojure/clojure "1.6.0"]
 [helpshift/gulfstream "0.2.1"]]
```

Trying to:

``` clojure
(require '[gulfstream.core :as gs])
```

results in:
`CompilerException java.lang.RuntimeException: No such var: reflect/context-class`

I tried it with Clojure 1.7.0 as well, and in that case I got a different CompilerException:
`CompilerException java.lang.Exception: namespace 'hara.object.base' not found, compiling:(hara/object/access.clj:1:1)`

**Comment by hoebat** [comment]
hmm... that's very annoying. It may be that there is another version of `hara.reflect` that has messed with  the loading (if you are using vinyasa/ultra, that's probably the most likely culprit)

Can you can add an explicit dependency for `[im.chit/hara.reflect "2.2.11"]`then try again to see if the problem has gone away?

**Comment by hoebat** [comment]
if that works for you, then I'll fix it for the next version

**Comment by luxbock** [comment]
Ahh... I totally forgot I was using vinyasa in my profiles.clj, and an older version at that. Once I upgraded to the latest version then the issue went away. I'll close this. Sorry for the confusion.

**Comment by hoebat** [comment]
No not at all. Thanks for bringing the issue to attention!
